import { StudentData } from './schoolData';

// -------------------------------------------------------------
// ថ្នាក់ទី ១ A (c-1-gen-a) - បឋមសិក្សា (30 សិស្ស, កើតឆ្នាំ ~2018)
// -------------------------------------------------------------
export const SEED_STUDENTS_GRADE_1: StudentData[] = [
  {
    studentNationalId: 'STU-G01-001',
    khmerName: 'ចាន់ ពិសិដ្ឋ',
    latinName: 'CHAN PISETH',
    gender: 'MALE',
    dob: new Date('2018-02-14'),
    pobProvince: 'រាជធានីភ្នំពេញ',
    pobDistrict: 'ខណ្ឌដូនពេញ',
    fatherName: 'ចាន់ សុខា',
    fatherOccupation: 'មន្ត្រីរាជការ',
    motherName: 'កែវ ស្រីពៅ',
    motherOccupation: 'អាជីវករ',
    guardianPhone: '012 341 001',
    rollNumber: 1,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-002',
    khmerName: 'សុខ ស្រីពេជ្រ',
    latinName: 'SOK SREY PICH',
    gender: 'FEMALE',
    dob: new Date('2018-05-20'),
    pobProvince: 'រាជធានីភ្នំពេញ',
    pobDistrict: 'ខណ្ឌ៧មករា',
    fatherName: 'សុខ ចាន់ថន',
    fatherOccupation: 'អាជីវករ',
    motherName: 'ម៉ៅ ចិន្តា',
    motherOccupation: 'មេផ្ទះ',
    guardianPhone: '089 667 002',
    rollNumber: 2,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-003',
    khmerName: 'ហេង វិបុល',
    latinName: 'HENG VIBOL',
    gender: 'MALE',
    dob: new Date('2018-01-10'),
    pobProvince: 'ខេត្តកណ្តាល',
    pobDistrict: 'ក្រុងតាខ្មៅ',
    fatherName: 'ហេង សម្បត្តិ',
    fatherOccupation: 'កសិករ',
    motherName: 'ឡុង ធីតា',
    motherOccupation: 'គ្រូបង្រៀន',
    guardianPhone: '017 889 003',
    rollNumber: 3,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-004',
    khmerName: 'គង់ ម៉ាលីកា',
    latinName: 'KONG MALIKA',
    gender: 'FEMALE',
    dob: new Date('2018-08-12'),
    pobProvince: 'រាជធានីភ្នំពេញ',
    pobDistrict: 'ខណ្ឌទួលគោក',
    fatherName: 'គង់ សុវណ្ណ',
    fatherOccupation: 'គ្រូបង្រៀន',
    motherName: 'សេង មុនីកា',
    motherOccupation: 'មន្ត្រីរាជការ',
    guardianPhone: '098 554 004',
    rollNumber: 4,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-005',
    khmerName: 'ម៉ៅ គឹមឡុង',
    latinName: 'MAO KIMLONG',
    gender: 'MALE',
    dob: new Date('2018-04-18'),
    pobProvince: 'ខេត្តកំពង់ចាម',
    pobDistrict: 'ស្រុកព្រៃឈរ',
    fatherName: 'ម៉ៅ វិចិត្រ',
    fatherOccupation: 'បុគ្គលិកក្រុមហ៊ុន',
    motherName: 'ទាវ សុផល',
    motherOccupation: 'បុគ្គលិកធនាគារ',
    guardianPhone: '070 223 005',
    rollNumber: 5,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-006',
    khmerName: 'ឈុន ស្រីនីត',
    latinName: 'CHHUN SREYNITH',
    gender: 'FEMALE',
    dob: new Date('2018-11-25'),
    pobProvince: 'រាជធានីភ្នំពេញ',
    pobDistrict: 'ខណ្ឌចំការមន',
    fatherName: 'ឈុន សំអាត',
    fatherOccupation: 'វិស្វករ',
    motherName: 'ង៉ែត សុភ័ក្រ',
    motherOccupation: 'កសិករ',
    guardianPhone: '011 445 006',
    rollNumber: 6,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-007',
    khmerName: 'តាំង ដារ៉ា',
    latinName: 'TANG DARA',
    gender: 'MALE',
    dob: new Date('2018-03-05'),
    pobProvince: 'រាជធានីភ្នំពេញ',
    pobDistrict: 'ខណ្ឌសែនសុខ',
    fatherName: 'តាំង ហុកសេង',
    fatherOccupation: 'ពាណិជ្ជករ',
    motherName: 'លឹម គឹមហួរ',
    motherOccupation: 'គិលានុបដ្ឋាយិកា',
    guardianPhone: '012 998 007',
    rollNumber: 7,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-008',
    khmerName: 'ស៊ុន ចរិយា',
    latinName: 'SUN CHORIYA',
    gender: 'FEMALE',
    dob: new Date('2018-07-19'),
    pobProvince: 'ខេត្តកណ្តាល',
    pobDistrict: 'ស្រុកកៀនស្វាយ',
    fatherName: 'ស៊ុន វណ្ណារ៉ា',
    fatherOccupation: 'វេជ្ជបណ្ឌិត',
    motherName: 'យឹម ស្រីនាង',
    motherOccupation: 'សហគ្រិន',
    guardianPhone: '097 334 008',
    rollNumber: 8,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-009',
    khmerName: 'លាង វឌ្ឍនៈ',
    latinName: 'LEANG VATHTHANAK',
    gender: 'MALE',
    dob: new Date('2018-09-30'),
    pobProvince: 'ខេត្តតាកែវ',
    pobDistrict: 'ស្រុកបាទី',
    fatherName: 'លាង សុវណ្ណ',
    fatherOccupation: 'អ្នកបើកបរ',
    motherName: 'សោម ចរិយា',
    motherOccupation: 'បុគ្គលិកក្រុមហ៊ុន',
    guardianPhone: '015 776 009',
    rollNumber: 9,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-010',
    khmerName: 'អ៊ុំ ពិសី',
    latinName: 'OUM PISEY',
    gender: 'FEMALE',
    dob: new Date('2018-06-14'),
    pobProvince: 'រាជធានីភ្នំពេញ',
    pobDistrict: 'ខណ្ឌមានជ័យ',
    fatherName: 'អ៊ុំ សារ៉េត',
    fatherOccupation: 'មេការសំណង់',
    motherName: 'ពៅ សុភី',
    motherOccupation: 'អ្នកកាត់ដេរ',
    guardianPhone: '085 221 010',
    rollNumber: 10,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-011',
    khmerName: 'ឌួង សុភ័ក្ត្រ',
    latinName: 'DUONG SOPHEAK',
    gender: 'MALE',
    dob: new Date('2018-10-08'),
    pobProvince: 'ខេត្តកំពង់ស្ពឺ',
    pobDistrict: 'ស្រុកច្បារមន',
    fatherName: 'ឌួង រិទ្ធី',
    fatherOccupation: 'មន្ត្រីរាជការ',
    motherName: 'លាង សុខេង',
    motherOccupation: 'អាជីវករ',
    guardianPhone: '077 889 011',
    rollNumber: 11,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-012',
    khmerName: 'នូ សុជាតា',
    latinName: 'NOU SOCHEATA',
    gender: 'FEMALE',
    dob: new Date('2018-12-01'),
    pobProvince: 'ខេត្តព្រៃវែង',
    pobDistrict: 'ស្រុកបាភ្នំ',
    fatherName: 'នូ សារុន',
    fatherOccupation: 'អាជីវករ',
    motherName: 'ហុង ពិសី',
    motherOccupation: 'មេផ្ទះ',
    guardianPhone: '096 443 012',
    rollNumber: 12,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-013',
    khmerName: 'ឡាយ រតនៈ',
    latinName: 'LAY RATTANAK',
    gender: 'MALE',
    dob: new Date('2018-01-22'),
    pobProvince: 'រាជធានីភ្នំពេញ',
    pobDistrict: 'ខណ្ឌពោធិ៍សែនជ័យ',
    fatherName: 'ឡាយ សុវណ្ណា',
    fatherOccupation: 'កសិករ',
    motherName: 'ជុំ ចរិយា',
    motherOccupation: 'គ្រូបង្រៀន',
    guardianPhone: '012 667 013',
    rollNumber: 13,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-014',
    khmerName: 'វ៉ាន់ ស្រីអូន',
    latinName: 'VAN SREY OUN',
    gender: 'FEMALE',
    dob: new Date('2018-04-09'),
    pobProvince: 'ខេត្តបាត់ដំបង',
    pobDistrict: 'ស្រុកសង្កែ',
    fatherName: 'វ៉ាន់ គង់',
    fatherOccupation: 'គ្រូបង្រៀន',
    motherName: 'សោម ធីតា',
    motherOccupation: 'មន្ត្រីរាជការ',
    guardianPhone: '098 112 014',
    rollNumber: 14,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-015',
    khmerName: 'ជា វិរៈ',
    latinName: 'CHEA VIRAK',
    gender: 'MALE',
    dob: new Date('2018-08-28'),
    pobProvince: 'ខេត្តកំពង់ឆ្នាំង',
    pobDistrict: 'ស្រុករលាប្អៀរ',
    fatherName: 'ជា សុវណ្ណ',
    fatherOccupation: 'បុគ្គលិកក្រុមហ៊ុន',
    motherName: 'ម៉ៅ គឹមលាង',
    motherOccupation: 'បុគ្គលិកធនាគារ',
    guardianPhone: '089 334 015',
    rollNumber: 15,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-016',
    khmerName: 'កែវ ធីតា',
    latinName: 'KEO THIDA',
    gender: 'FEMALE',
    dob: new Date('2018-05-17'),
    pobProvince: 'រាជធានីភ្នំពេញ',
    pobDistrict: 'ខណ្ឌច្បារអំពៅ',
    fatherName: 'កែវ សុជាតិ',
    fatherOccupation: 'វិស្វករ',
    motherName: 'ស៊ុន ផល្លា',
    motherOccupation: 'កសិករ',
    guardianPhone: '017 556 016',
    rollNumber: 16,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-017',
    khmerName: 'រស់ ពិសិដ្ឋ',
    latinName: 'ROS PISETH',
    gender: 'MALE',
    dob: new Date('2018-03-24'),
    pobProvince: 'ខេត្តសៀមរាប',
    pobDistrict: 'ក្រុងសៀមរាប',
    fatherName: 'រស់ គឹមស៊ន',
    fatherOccupation: 'ពាណិជ្ជករ',
    motherName: 'ខៀវ គឹមអាន',
    motherOccupation: 'គិលានុបដ្ឋាយិកា',
    guardianPhone: '010 778 017',
    rollNumber: 17,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-018',
    khmerName: 'សេង លីដា',
    latinName: 'SENG LYDA',
    gender: 'FEMALE',
    dob: new Date('2018-09-15'),
    pobProvince: 'រាជធានីភ្នំពេញ',
    pobDistrict: 'ខណ្ឌដូនពេញ',
    fatherName: 'សេង វណ្ណឌី',
    fatherOccupation: 'វេជ្ជបណ្ឌិត',
    motherName: 'ឈុន សុភ័ក្ត្រ',
    motherOccupation: 'សហគ្រិន',
    guardianPhone: '012 889 018',
    rollNumber: 18,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-019',
    khmerName: 'ណុប សុខា',
    latinName: 'NOP SOKHA',
    gender: 'MALE',
    dob: new Date('2018-07-07'),
    pobProvince: 'ខេត្តកណ្តាល',
    pobDistrict: 'ស្រុកពញាឮ',
    fatherName: 'ណុប ផល',
    fatherOccupation: 'អ្នកបើកបរ',
    motherName: 'ចាន់ ស្រីអូន',
    motherOccupation: 'បុគ្គលិកក្រុមហ៊ុន',
    guardianPhone: '077 990 019',
    rollNumber: 19,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-020',
    khmerName: 'យឹម ស្រីម៉ៅ',
    latinName: 'YIM SREYMAO',
    gender: 'FEMALE',
    dob: new Date('2018-11-11'),
    pobProvince: 'ខេត្តកំពង់ចាម',
    pobDistrict: 'ស្រុកកោះសូទិន',
    fatherName: 'យឹម វិចិត្រ',
    fatherOccupation: 'មេការសំណង់',
    motherName: 'ម៉ី សុខុម',
    motherOccupation: 'អ្នកកាត់ដេរ',
    guardianPhone: '061 223 020',
    rollNumber: 20,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-021',
    khmerName: 'អ៊ុក សុធា',
    latinName: 'OUK SOTHEA',
    gender: 'MALE',
    dob: new Date('2018-02-28'),
    pobProvince: 'រាជធានីភ្នំពេញ',
    pobDistrict: 'ខណ្ឌទួលគោក',
    fatherName: 'អ៊ុក គឹមហេង',
    fatherOccupation: 'មន្ត្រីរាជការ',
    motherName: 'ចាន់ ស្រីមុំ',
    motherOccupation: 'អាជីវករ',
    guardianPhone: '012 445 021',
    rollNumber: 21,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-022',
    khmerName: 'ហុង ស្រីលក្ខណ៍',
    latinName: 'HONG SREYLEAK',
    gender: 'FEMALE',
    dob: new Date('2018-06-03'),
    pobProvince: 'រាជធានីភ្នំពេញ',
    pobDistrict: 'ខណ្ឌសែនសុខ',
    fatherName: 'ហុង សារ៉ុម',
    fatherOccupation: 'អាជីវករ',
    motherName: 'នូ សារុន',
    motherOccupation: 'មេផ្ទះ',
    guardianPhone: '015 667 022',
    rollNumber: 22,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-023',
    khmerName: 'លី រិទ្ធី',
    latinName: 'LY RITHY',
    gender: 'MALE',
    dob: new Date('2018-10-19'),
    pobProvince: 'ខេត្តតាកែវ',
    pobDistrict: 'ស្រុកទ្រាំង',
    fatherName: 'លី សុខុម',
    fatherOccupation: 'កសិករ',
    motherName: 'ទេព ធីតា',
    motherOccupation: 'គ្រូបង្រៀន',
    guardianPhone: '097 889 023',
    rollNumber: 23,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-024',
    khmerName: 'ទេព មុនីរ័ត្ន',
    latinName: 'TEP MONIROTH',
    gender: 'FEMALE',
    dob: new Date('2018-01-15'),
    pobProvince: 'រាជធានីភ្នំពេញ',
    pobDistrict: 'ខណ្ឌចំការមន',
    fatherName: 'ទេព សុវណ្ណ',
    fatherOccupation: 'គ្រូបង្រៀន',
    motherName: 'អ៊ុក ស្រីពេជ្រ',
    motherOccupation: 'មន្ត្រីរាជការ',
    guardianPhone: '070 112 024',
    rollNumber: 24,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-025',
    khmerName: 'ពេជ្រ ឧត្តម',
    latinName: 'PICH OUDOM',
    gender: 'MALE',
    dob: new Date('2018-05-09'),
    pobProvince: 'ខេត្តកំពង់ធំ',
    pobDistrict: 'ស្រុកស្ទោង',
    fatherName: 'ពេជ្រ សារ៉េត',
    fatherOccupation: 'បុគ្គលិកក្រុមហ៊ុន',
    motherName: 'សេង ផល្លា',
    motherOccupation: 'បុគ្គលិកធនាគារ',
    guardianPhone: '089 443 025',
    rollNumber: 25,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-026',
    khmerName: 'សោម ចរិយា',
    latinName: 'SOM CHORIYA',
    gender: 'FEMALE',
    dob: new Date('2018-08-22'),
    pobProvince: 'ខេត្តសៀមរាប',
    pobDistrict: 'ស្រុកប្រាសាទបាគង',
    fatherName: 'សោម ប៊ុនធឿន',
    fatherOccupation: 'វិស្វករ',
    motherName: 'ម៉ៅ វណ្ណី',
    motherOccupation: 'កសិករ',
    guardianPhone: '016 554 026',
    rollNumber: 26,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-027',
    khmerName: 'ខៀវ វិរៈបុត្រ',
    latinName: 'KHIEV VIRAKBOT',
    gender: 'MALE',
    dob: new Date('2018-12-18'),
    pobProvince: 'រាជធានីភ្នំពេញ',
    pobDistrict: 'ខណ្ឌមានជ័យ',
    fatherName: 'ខៀវ គឹមអាន',
    fatherOccupation: 'ពាណិជ្ជករ',
    motherName: 'រស់ សុភី',
    motherOccupation: 'គិលានុបដ្ឋាយិកា',
    guardianPhone: '012 334 027',
    rollNumber: 27,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-028',
    khmerName: 'ភួង សុជាតា',
    latinName: 'PHUONG SOCHEATA',
    gender: 'FEMALE',
    dob: new Date('2018-04-26'),
    pobProvince: 'ខេត្តកំពង់ចាម',
    pobDistrict: 'ក្រុងកំពង់ចាម',
    fatherName: 'ភួង សំអុល',
    fatherOccupation: 'វេជ្ជបណ្ឌិត',
    motherName: 'ចាន់ ស្រីមុំ',
    motherOccupation: 'សហគ្រិន',
    guardianPhone: '098 776 028',
    rollNumber: 28,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-029',
    khmerName: 'អៀង ប៊ុនរ៉ុង',
    latinName: 'EANG BUNRONG',
    gender: 'MALE',
    dob: new Date('2018-09-02'),
    pobProvince: 'ខេត្តកោះកុង',
    pobDistrict: 'ក្រុងខេមរភូមិន្ទ',
    fatherName: 'អៀង វណ្ណា',
    fatherOccupation: 'អ្នកបើកបរ',
    motherName: 'ឡាយ ស្រីពៅ',
    motherOccupation: 'បុគ្គលិកក្រុមហ៊ុន',
    guardianPhone: '085 990 029',
    rollNumber: 29,
    classId: 'c-1-gen-a',
  },
  {
    studentNationalId: 'STU-G01-030',
    khmerName: 'ឡុង ស្រីរ័ត្ន',
    latinName: 'LONG SREYROTH',
    gender: 'FEMALE',
    dob: new Date('2018-03-11'),
    pobProvince: 'រាជធានីភ្នំពេញ',
    pobDistrict: 'ខណ្ឌ៧មករា',
    fatherName: 'ឡុង វិចិត្រ',
    fatherOccupation: 'មេការសំណង់',
    motherName: 'ស៊ុន ធីតា',
    motherOccupation: 'អ្នកកាត់ដេរ',
    guardianPhone: '017 221 030',
    rollNumber: 30,
    classId: 'c-1-gen-a',
  },
];

// -------------------------------------------------------------
const SEED_FATHER_OCCUPATIONS = [
  'មន្ត្រីរាជការ',
  'អាជីវករ',
  'កសិករ',
  'គ្រូបង្រៀន',
  'បុគ្គលិកក្រុមហ៊ុន',
  'វិស្វករ',
  'ពាណិជ្ជករ',
  'វេជ្ជបណ្ឌិត',
  'អ្នកបើកបរ',
  'មេការសំណង់',
];

const SEED_MOTHER_OCCUPATIONS = [
  'អាជីវករ',
  'មេផ្ទះ',
  'គ្រូបង្រៀន',
  'មន្ត្រីរាជការ',
  'បុគ្គលិកធនាគារ',
  'កសិករ',
  'គិលានុបដ្ឋាយិកា',
  'សហគ្រិន',
  'បុគ្គលិកក្រុមហ៊ុន',
  'អ្នកកាត់ដេរ',
];

// ថ្នាក់ទី ៤ A (c-4-gen-a) - បឋមសិក្សា (32 សិស្ស, កើតឆ្នាំ ~2015)
// -------------------------------------------------------------
export const SEED_STUDENTS_GRADE_4: StudentData[] = Array.from({ length: 32 }, (_, idx) => {
  const num = idx + 1;
  const isFemale = num % 2 === 0;
  const idStr = String(num).padStart(3, '0');
  const maleNames = ['សុខ រិទ្ធី', 'ចាន់ សុភ័ក្ត្រ', 'ហេង វិបុល', 'គង់ វណ្ណៈ', 'ម៉ៅ ពិសិដ្ឋ', 'ឈុន សម្បត្តិ', 'តាំង គីមឡុង', 'ស៊ុន វឌ្ឍនៈ', 'លាង រតនៈ', 'អ៊ុំ វិរៈ', 'ឌួង ចាន់ដារ៉ា', 'នូ ប៊ុនធឿន', 'ឡាយ ឧត្តម', 'វ៉ាន់ សុខុម', 'ជា សុវណ្ណារ៉ា', 'រស់ ពិសី'];
  const femaleNames = ['កែវ ធីតា', 'សុខ ស្រីពេជ្រ', 'ហេង សុជាតា', 'គង់ ម៉ាលីកា', 'ម៉ៅ ចិន្តា', 'ឈុន ស្រីមុំ', 'តាំង ស្រីនីត', 'ស៊ុន ចរិយា', 'លាង មុនីកា', 'អ៊ុំ ពិសី', 'ឌួង ចាន់ណា', 'នូ សុជាតា', 'ឡាយ ស្រីកែវ', 'វ៉ាន់ ស្រីអូន', 'ជា គឹមហួរ', 'រស់ ស្រីលក្ខណ៍'];
  const khmerName = isFemale ? femaleNames[idx % femaleNames.length] : maleNames[idx % maleNames.length];
  const latinName = isFemale ? `STUDENT G4 F${num}` : `STUDENT G4 M${num}`;
  const provinces = ['រាជធានីភ្នំពេញ', 'ខេត្តកណ្តាល', 'ខេត្តកំពង់ចាម', 'ខេត្តតាកែវ', 'ខេត្តសៀមរាប', 'ខេត្តបាត់ដំបង', 'ខេត្តកំពង់ធំ'];
  const province = provinces[idx % provinces.length];

  return {
    studentNationalId: `STU-G04-${idStr}`,
    khmerName: `${khmerName} (៤A-${num})`,
    latinName: `${latinName}`,
    gender: isFemale ? 'FEMALE' : 'MALE',
    dob: new Date(2015, (idx % 12), (idx % 27) + 1),
    pobProvince: province,
    pobDistrict: 'ស្រុក/ខណ្ឌគំរូ',
    fatherName: `ឪពុក ${khmerName}`,
    fatherOccupation: SEED_FATHER_OCCUPATIONS[idx % SEED_FATHER_OCCUPATIONS.length],
    motherName: `ម្តាយ ${khmerName}`,
    motherOccupation: SEED_MOTHER_OCCUPATIONS[idx % SEED_MOTHER_OCCUPATIONS.length],
    guardianPhone: `012 440 ${idStr}`,
    rollNumber: num,
    classId: 'c-4-gen-a',
  };
});

// -------------------------------------------------------------
// ថ្នាក់ទី ៦ A (c-6-gen-a) - បឋមសិក្សា (34 សិស្ស, កើតឆ្នាំ ~2013)
// -------------------------------------------------------------
export const SEED_STUDENTS_GRADE_6: StudentData[] = Array.from({ length: 34 }, (_, idx) => {
  const num = idx + 1;
  const isFemale = num % 2 === 0;
  const idStr = String(num).padStart(3, '0');
  const maleNames = ['អ៊ុក សុធារ៉ា', 'ឡាយ ប៊ុនរ៉ុង', 'ហុង សម្បត្តិ', 'សេង វិចិត្រ', 'កែវ ឧត្តម', 'ឌួង វឌ្ឍនៈ', 'ណុប សុខុម', 'ជា ពិសិដ្ឋ', 'ម៉ៅ រតនៈ', 'ឈុន វណ្ណៈ', 'តាំង ដារ៉ា', 'ស៊ុន វិបុល', 'លាង សុភ័ក្ត្រ', 'អ៊ុំ សារ៉េត', 'វ៉ាន់ គង់', 'ពេជ្រ សារ៉ុម', 'ភួង សំអុល'];
  const femaleNames = ['សេង មុនីកា', 'សោម ចរិយា', 'សុខ ចាន់ដារា', 'ស៊ុន ស្រីកែវ', 'ហេង សុជាតា', 'ហុង ពិសី', 'យឹម ស្រីនីត', 'លឹម គឹមហួរ', 'ឌួង ចាន់ណា', 'ឈុន ស្រីមុំ', 'កែវ ធីតា', 'អ៊ុំ រតនា', 'ម៉ៅ គឹមលាង', 'សេង ស្រីនាង', 'លាង សុខេង', 'ចាន់ ស្រីអូន', 'ង៉ែត សុភ័ក្រ'];
  const khmerName = isFemale ? femaleNames[idx % femaleNames.length] : maleNames[idx % maleNames.length];
  const latinName = isFemale ? `STUDENT G6 F${num}` : `STUDENT G6 M${num}`;
  const provinces = ['រាជធានីភ្នំពេញ', 'ខេត្តកណ្តាល', 'ខេត្តកំពង់ចាម', 'ខេត្តតាកែវ', 'ខេត្តសៀមរាប', 'ខេត្តបាត់ដំបង', 'ខេត្តព្រៃវែង'];
  const province = provinces[idx % provinces.length];

  return {
    studentNationalId: `STU-G06-${idStr}`,
    khmerName: `${khmerName} (៦A-${num})`,
    latinName: `${latinName}`,
    gender: isFemale ? 'FEMALE' : 'MALE',
    dob: new Date(2013, (idx % 12), (idx % 27) + 1),
    pobProvince: province,
    pobDistrict: 'ស្រុក/ខណ្ឌគំរូ',
    fatherName: `ឪពុក ${khmerName}`,
    fatherOccupation: SEED_FATHER_OCCUPATIONS[idx % SEED_FATHER_OCCUPATIONS.length],
    motherName: `ម្តាយ ${khmerName}`,
    motherOccupation: SEED_MOTHER_OCCUPATIONS[idx % SEED_MOTHER_OCCUPATIONS.length],
    guardianPhone: `017 660 ${idStr}`,
    rollNumber: num,
    classId: 'c-6-gen-a',
  };
});

// -------------------------------------------------------------
// ថ្នាក់ទី ១០ A (c-10-gen-a) - ទូទៅ (35 សិស្ស, កើតឆ្នាំ ~2009)
// -------------------------------------------------------------
export const SEED_STUDENTS_GRADE_10: StudentData[] = Array.from({ length: 35 }, (_, idx) => {
  const num = idx + 1;
  const isFemale = num % 2 === 0;
  const idStr = String(num).padStart(3, '0');
  const maleNames = ['សុខ វិបុល', 'ចាន់ សុភ័ក្ត្រ', 'ហេង ពិសិដ្ឋ', 'គង់ វណ្ណៈ', 'ម៉ៅ ឧត្តម', 'ឈុន សម្បត្តិ', 'តាំង គីមឡុង', 'ស៊ុន វឌ្ឍនៈ', 'លាង រតនៈ', 'អ៊ុំ វិរៈ', 'ឌួង ចាន់ដារ៉ា', 'នូ ប៊ុនធឿន', 'ឡាយ ឧត្តម', 'វ៉ាន់ សុខុម', 'ជា សុវណ្ណារ៉ា', 'រស់ ពិសី', 'ពេជ្រ សារ៉េត', 'អៀង ប៊ុនរ៉ុង'];
  const femaleNames = ['កែវ ធីតា', 'សុខ ស្រីពេជ្រ', 'ហេង សុជាតា', 'គង់ ម៉ាលីកា', 'ម៉ៅ ចិន្តា', 'ឈុន ស្រីមុំ', 'តាំង ស្រីនីត', 'ស៊ុន ចរិយា', 'លាង មុនីកា', 'អ៊ុំ ពិសី', 'ឌួង ចាន់ណា', 'នូ សុជាតា', 'ឡាយ ស្រីកែវ', 'វ៉ាន់ ស្រីអូន', 'ជា គឹមហួរ', 'រស់ ស្រីលក្ខណ៍', 'សេង លីដា'];
  const khmerName = isFemale ? femaleNames[idx % femaleNames.length] : maleNames[idx % maleNames.length];
  const latinName = isFemale ? `STUDENT G10 F${num}` : `STUDENT G10 M${num}`;
  const provinces = ['រាជធានីភ្នំពេញ', 'ខេត្តកណ្តាល', 'ខេត្តកំពង់ចាម', 'ខេត្តកំពង់ឆ្នាំង', 'ខេត្តតាកែវ', 'ខេត្តសៀមរាប', 'ខេត្តបាត់ដំបង'];
  const province = provinces[idx % provinces.length];

  return {
    studentNationalId: `STU-G10-${idStr}`,
    khmerName: `${khmerName} (១០A-${num})`,
    latinName: `${latinName}`,
    gender: isFemale ? 'FEMALE' : 'MALE',
    dob: new Date(2009, (idx % 12), (idx % 27) + 1),
    pobProvince: province,
    pobDistrict: 'ស្រុក/ខណ្ឌគំរូ',
    fatherName: `ឪពុក ${khmerName}`,
    fatherOccupation: SEED_FATHER_OCCUPATIONS[idx % SEED_FATHER_OCCUPATIONS.length],
    motherName: `ម្តាយ ${khmerName}`,
    motherOccupation: SEED_MOTHER_OCCUPATIONS[idx % SEED_MOTHER_OCCUPATIONS.length],
    guardianPhone: `098 100 ${idStr}`,
    rollNumber: num,
    classId: 'c-10-gen-a',
  };
});

// -------------------------------------------------------------
// ថ្នាក់ទី ១២ សង្គម ១ (c-12-soc-1) (32 សិស្ស, កើតឆ្នាំ ~2006)
// -------------------------------------------------------------
export const SEED_STUDENTS_GRADE_12: StudentData[] = Array.from({ length: 32 }, (_, idx) => {
  const num = idx + 1;
  const isFemale = num % 2 === 0;
  const idStr = String(num).padStart(3, '0');
  const maleNames = ['ហុង សម្បត្តិ', 'សេង វណ្ណឌី', 'កែវ សុខា', 'ឈុន ពិសិដ្ឋ', 'លី សុខុម', 'ស៊ុន សុវណ្ណារ៉ា', 'ម៉ៅ ចិន្តា', 'អ៊ុក សុធារ៉ា', 'ឡាយ ប៊ុនរ៉ុង', 'ឌួង ចាន់ណា', 'តាំង គីមឡុង', 'ជា សុភ័ក្ត្រ', 'គង់ វណ្ណៈ', 'រស់ ពិសិដ្ឋ', 'អ៊ុំ វិបុល', 'វ៉ាន់ វឌ្ឍនៈ'];
  const femaleNames = ['អ៊ុក ស្រីពេជ្រ', 'ទេព ធីតា', 'ឈុន សុភ័ក្ត្រ', 'កែវ ធីតា', 'ស៊ុន ស្រីកែវ', 'ហេង សុជាតា', 'ហុង ពិសី', 'សេង មុនីកា', 'សោម ចរិយា', 'យឹម ស្រីនីត', 'លឹម គឹមហួរ', 'ឈុន ស្រីមុំ', 'ឌួង ចាន់ណា', 'នូ សុជាតា', 'ឡាយ សុផល', 'ពៅ សុភី'];
  const khmerName = isFemale ? femaleNames[idx % femaleNames.length] : maleNames[idx % maleNames.length];
  const latinName = isFemale ? `STUDENT G12 F${num}` : `STUDENT G12 M${num}`;
  const provinces = ['រាជធានីភ្នំពេញ', 'ខេត្តកណ្តាល', 'ខេត្តកំពង់ចាម', 'ខេត្តកំពង់ឆ្នាំង', 'ខេត្តតាកែវ', 'ខេត្តសៀមរាប', 'ខេត្តបាត់ដំបង'];
  const province = provinces[idx % provinces.length];

  return {
    studentNationalId: `STU-G12-${idStr}`,
    khmerName: `${khmerName} (១២ស-${num})`,
    latinName: `${latinName}`,
    gender: isFemale ? 'FEMALE' : 'MALE',
    dob: new Date(2006, (idx % 12), (idx % 27) + 1),
    pobProvince: province,
    pobDistrict: 'ស្រុក/ខណ្ឌគំរូ',
    fatherName: `ឪពុក ${khmerName}`,
    fatherOccupation: SEED_FATHER_OCCUPATIONS[idx % SEED_FATHER_OCCUPATIONS.length],
    motherName: `ម្តាយ ${khmerName}`,
    motherOccupation: SEED_MOTHER_OCCUPATIONS[idx % SEED_MOTHER_OCCUPATIONS.length],
    guardianPhone: `077 120 ${idStr}`,
    rollNumber: num,
    classId: 'c-12-soc-1',
  };
});
