/**
 * MoEYS Cambodia Official Public Holidays & Academic Calendar Events
 * Pure Client-Safe TypeScript Module
 */

export type HolidayType = 'PUBLIC_HOLIDAY' | 'ACADEMIC_EVENT' | 'EXAM_PERIOD' | 'VACATION' | 'SCHOOL_EVENT';

export interface HolidayData {
  id: string;
  titleKhmer: string;
  titleEnglish?: string;
  dateFrom: string; // YYYY-MM-DD
  dateTo: string;   // YYYY-MM-DD
  type: HolidayType;
  isDayOff: boolean;
  description?: string;
  academicYear?: string;
}

export const OFFICIAL_CAMBODIA_HOLIDAYS_2024_2025: HolidayData[] = [
  // Semester 1 Academic Events & Holidays
  {
    id: 'moeys-school-open-2024',
    titleKhmer: 'ពិធីបើកបវេសនកាលឆ្នាំសិក្សាថ្មី ២០២៤ - ២០២៥',
    titleEnglish: 'Opening of Academic Year 2024-2025',
    dateFrom: '2024-11-01',
    dateTo: '2024-11-01',
    type: 'ACADEMIC_EVENT',
    isDayOff: false,
    description: 'ថ្ងៃបើកបវេសនកាលផ្លូវការគ្រប់គ្រឹះស្ថានសិក្សាចំណេះទូទៅទូទាំងប្រទេស',
    academicYear: '២០២៤ - ២០២៥',
  },
  {
    id: 'hol-independence-day-2024',
    titleKhmer: 'ពិធីបុណ្យឯករាជ្យជាតិ (ខួបលើកទី៧១)',
    titleEnglish: 'National Independence Day',
    dateFrom: '2024-11-09',
    dateTo: '2024-11-09',
    type: 'PUBLIC_HOLIDAY',
    isDayOff: true,
    description: 'ទិវាបុណ្យឯករាជ្យជាតិ ៩ វិច្ឆិកា',
    academicYear: '២០២៤ - ២០២៥',
  },
  {
    id: 'hol-water-festival-2024',
    titleKhmer: 'ព្រះរាជពិធីបុណ្យអុំទូក បណ្តែតប្រទីប និងសំពះព្រះខែ អកអំបុក',
    titleEnglish: 'Water and Moon Festival',
    dateFrom: '2024-11-14',
    dateTo: '2024-11-16',
    type: 'PUBLIC_HOLIDAY',
    isDayOff: true,
    description: 'ព្រះរាជពិធីបុណ្យប្រពៃណីជាតិ រយៈពេល ៣ ថ្ងៃ',
    academicYear: '២០២៤ - ២០២៥',
  },
  {
    id: 'hol-international-new-year-2025',
    titleKhmer: 'ទិវាចូលឆ្នាំសកល',
    titleEnglish: 'International New Year Day',
    dateFrom: '2025-01-01',
    dateTo: '2025-01-01',
    type: 'PUBLIC_HOLIDAY',
    isDayOff: true,
    description: 'ទិវាចូលឆ្នាំថ្មីសកល ១ មករា',
    academicYear: '២០២៤ - ២០២៥',
  },
  {
    id: 'hol-victory-day-2025',
    titleKhmer: 'ទិវាជ័យជម្នះលើរបបប្រល័យពូជសាសន៍',
    titleEnglish: 'Victory Day over Genocide',
    dateFrom: '2025-01-07',
    dateTo: '2025-01-07',
    type: 'PUBLIC_HOLIDAY',
    isDayOff: true,
    description: 'ទិវា ៧ មករា ជ័យជម្នះលើរបបប្រល័យពូជសាសន៍',
    academicYear: '២០២៤ - ២០២៥',
  },
  {
    id: 'moeys-exam-sem1-2025',
    titleKhmer: 'ការប្រឡងបញ្ចប់ឆមាសទី១',
    titleEnglish: 'Semester 1 Final Examination',
    dateFrom: '2025-03-03',
    dateTo: '2025-03-07',
    type: 'EXAM_PERIOD',
    isDayOff: false,
    description: 'សម័យប្រឡងឆមាសទី១ សម្រាប់កម្រិតបឋម និងមធ្យមសិក្សា',
    academicYear: '២០២៤ - ២០២៥',
  },
  {
    id: 'hol-women-day-2025',
    titleKhmer: 'ទិវាអន្តរជាតិនារី ៨ មីនា',
    titleEnglish: 'International Women Day',
    dateFrom: '2025-03-08',
    dateTo: '2025-03-08',
    type: 'PUBLIC_HOLIDAY',
    isDayOff: true,
    description: 'ទិវាសិទ្ធិនារីអន្តរជាតិ',
    academicYear: '២០២៤ - ២០២៥',
  },
  {
    id: 'moeys-break-sem1-2025',
    titleKhmer: 'វិស្សមកាលតូច (ដំណាច់ឆមាសទី១)',
    titleEnglish: 'Short Vacation / Mid-Year Break',
    dateFrom: '2025-04-07',
    dateTo: '2025-04-20',
    type: 'VACATION',
    isDayOff: true,
    description: 'វិស្សមកាលតូច រួមទាំងពិធីបុណ្យចូលឆ្នាំថ្មីប្រពៃណីជាតិខ្មែរ',
    academicYear: '២០២៤ - ២០២៥',
  },
  {
    id: 'hol-khmer-new-year-2025',
    titleKhmer: 'ពិធីបុណ្យចូលឆ្នាំថ្មី ប្រពៃណីជាតិខ្មែរ',
    titleEnglish: 'Khmer New Year Days',
    dateFrom: '2025-04-14',
    dateTo: '2025-04-16',
    type: 'PUBLIC_HOLIDAY',
    isDayOff: true,
    description: 'ពិធីបុណ្យចូលឆ្នាំប្រពៃណីជាតិខ្មែរ រយៈពេល ៣ ថ្ងៃ',
    academicYear: '២០២៤ - ២០២៥',
  },
  {
    id: 'hol-labor-day-2025',
    titleKhmer: 'ទិវាពលកម្មអន្តរជាតិ ១ ឧសភា',
    titleEnglish: 'International Labor Day',
    dateFrom: '2025-05-01',
    dateTo: '2025-05-01',
    type: 'PUBLIC_HOLIDAY',
    isDayOff: true,
    description: 'ទិវាពលកម្មអន្តរជាតិ ១ ឧសភា',
    academicYear: '២០២៤ - ២០២៥',
  },
  {
    id: 'hol-visak-bochea-2025',
    titleKhmer: 'ពិធីបុណ្យវិសាខបូជា',
    titleEnglish: 'Visak Bochea Day',
    dateFrom: '2025-05-12',
    dateTo: '2025-05-12',
    type: 'PUBLIC_HOLIDAY',
    isDayOff: true,
    description: 'ទិវាបុណ្យសាសនាជាតិ វិសាខបូជា',
    academicYear: '២០២៤ - ២០២៥',
  },
  {
    id: 'hol-king-birthday-2025',
    titleKhmer: 'ព្រះរាជពិធីបុណ្យចម្រើនព្រះជន្ម ព្រះករុណា ព្រះបាទសម្តេចព្រះបរមនាថ នរោត្តម សីហមុនី',
    titleEnglish: 'King Norodom Sihamoni Birthday',
    dateFrom: '2025-05-14',
    dateTo: '2025-05-14',
    type: 'PUBLIC_HOLIDAY',
    isDayOff: true,
    description: 'ព្រះរាជពិធីបុណ្យចម្រើនព្រះជន្មព្រះមហាក្សត្រ',
    academicYear: '២០២៤ - ២០២៥',
  },
  {
    id: 'hol-royal-plowing-2025',
    titleKhmer: 'ព្រះរាជពិធីច្រត់ព្រះនង្គ័ល',
    titleEnglish: 'Royal Plowing Ceremony',
    dateFrom: '2025-05-16',
    dateTo: '2025-05-16',
    type: 'PUBLIC_HOLIDAY',
    isDayOff: true,
    description: 'ព្រះរាជពិធីច្រត់ព្រះនង្គ័ល',
    academicYear: '២០២៤ - ២០២៥',
  },
  {
    id: 'hol-queen-mother-birthday-2025',
    titleKhmer: 'ព្រះរាជពិធីបុណ្យចម្រើនព្រះជន្ម សម្តេចព្រះមហាក្សត្រី នរោត្តម មុនិនាថ សីហនុ ព្រះវររាជមាតាជាតិខ្មែរ',
    titleEnglish: 'Queen Mother Norodom Monineath Sihanouk Birthday',
    dateFrom: '2025-06-18',
    dateTo: '2025-06-18',
    type: 'PUBLIC_HOLIDAY',
    isDayOff: true,
    description: 'ព្រះរាជពិធីបុណ្យចម្រើនព្រះជន្មសម្តេចម៉ែ',
    academicYear: '២០២៤ - ២០២៥',
  },
  {
    id: 'moeys-exam-sem2-2025',
    titleKhmer: 'ការប្រឡងបញ្ចប់ឆមាសទី២',
    titleEnglish: 'Semester 2 Final Examination',
    dateFrom: '2025-07-07',
    dateTo: '2025-07-11',
    type: 'EXAM_PERIOD',
    isDayOff: false,
    description: 'សម័យប្រឡងឆមាសទី២ បញ្ចប់ឆ្នាំសិក្សា',
    academicYear: '២០២៤ - ២០២៥',
  },
  {
    id: 'moeys-exam-dip-2025',
    titleKhmer: 'ការប្រឡងសញ្ញាបត្រមធ្យមសិក្សាបឋមភូមិ (ឌីប្លូម)',
    titleEnglish: 'Lower Secondary Diploma Exam (Grade 9)',
    dateFrom: '2025-07-28',
    dateTo: '2025-07-29',
    type: 'EXAM_PERIOD',
    isDayOff: false,
    description: 'សម័យប្រឡងឌីប្លូមថ្នាក់ទី ៩ ទូទាំងប្រទេស',
    academicYear: '២០២៤ - ២០២៥',
  },
  {
    id: 'moeys-summer-vacation-2025',
    titleKhmer: 'វិស្សមកាលធំ (ដំណាច់ឆ្នាំសិក្សា)',
    titleEnglish: 'Grand Vacation / Summer Recess',
    dateFrom: '2025-08-01',
    dateTo: '2025-10-31',
    type: 'VACATION',
    isDayOff: true,
    description: 'វិស្សមកាលធំ សម្រាប់សិស្សានុសិស្ស និងលោកគ្រូ-អ្នកគ្រូ',
    academicYear: '២០២៤ - ២០២៥',
  },
  {
    id: 'moeys-exam-bac2-2025',
    titleKhmer: 'ការប្រឡងសញ្ញាបត្រមធ្យមសិក្សាទុតិយភូមិ (បាក់ឌុប)',
    titleEnglish: 'Upper Secondary National Exam (Bac II - Grade 12)',
    dateFrom: '2025-08-18',
    dateTo: '2025-08-19',
    type: 'EXAM_PERIOD',
    isDayOff: false,
    description: 'សម័យប្រឡងសញ្ញាបត្របាក់ឌុបថ្នាក់ទី ១២ ទូទាំងប្រទេស',
    academicYear: '២០២៤ - ២០២៥',
  },
  {
    id: 'hol-constitution-day-2025',
    titleKhmer: 'ទិវាប្រកាសរដ្ឋធម្មនុញ្ញ ២៤ កញ្ញា',
    titleEnglish: 'Constitutional Day',
    dateFrom: '2025-09-24',
    dateTo: '2025-09-24',
    type: 'PUBLIC_HOLIDAY',
    isDayOff: true,
    description: 'ទិវាប្រកាសរដ្ឋធម្មនុញ្ញនៃព្រះរាជាណាចក្រកម្ពុជា',
    academicYear: '២០២៤ - ២០២៥',
  },
  {
    id: 'hol-pchum-ben-2025',
    titleKhmer: 'ពិធីបុណ្យភ្ជុំបិណ្ឌ',
    titleEnglish: 'Pchum Ben Festival Days',
    dateFrom: '2025-09-21',
    dateTo: '2025-09-23',
    type: 'PUBLIC_HOLIDAY',
    isDayOff: true,
    description: 'ពិធីបុណ្យកាន់បិណ្ឌ និងភ្ជុំបិណ្ឌប្រពៃណីជាតិ រយៈពេល ៣ ថ្ងៃ',
    academicYear: '២០២៤ - ២០២៥',
  },
  {
    id: 'hol-commemoration-king-father-2025',
    titleKhmer: 'ទិវាប្រារព្ធពិធីគោរពព្រះវិញ្ញាណក្ខន្ធ ព្រះករុណា ព្រះបាទសម្តេចព្រះ នរោត្តម សីហនុ ព្រះបរមរតនកោដ្ឋ',
    titleEnglish: 'Commemoration Day of the King Father',
    dateFrom: '2025-10-15',
    dateTo: '2025-10-15',
    type: 'PUBLIC_HOLIDAY',
    isDayOff: true,
    description: 'ទិវាគោរពព្រះវិញ្ញាណក្ខន្ធ ព្រះបរមរតនកោដ្ឋ',
    academicYear: '២០២៤ - ២០២៥',
  },
  {
    id: 'hol-coronation-day-2025',
    titleKhmer: 'ព្រះរាជពិធីគ្រងរាជសម្បត្តិ ព្រះករុណា ព្រះបាទសម្តេចព្រះបរមនាថ នរោត្តម សីហមុនី',
    titleEnglish: 'Coronation Day of King Sihamoni',
    dateFrom: '2025-10-29',
    dateTo: '2025-10-29',
    type: 'PUBLIC_HOLIDAY',
    isDayOff: true,
    description: 'ទិវាខួបនៃការគ្រងរាជសម្បត្តិព្រះមហាក្សត្រ',
    academicYear: '២០២៤ - ២០២៥',
  },
];
