/**
 * MoEYS Cambodia Official Public Holidays & Academic Calendar Events Engine
 * Supports automated holiday & academic event calculation for any year (2024-2035+),
 * including fixed solar dates, official Khmer lunar calculations, and continuous auto-updates.
 */

export type HolidayType = 'PUBLIC_HOLIDAY' | 'ACADEMIC_EVENT' | 'EXAM_PERIOD' | 'VACATION' | 'SCHOOL_EVENT';

export interface HolidayData {
  id: string;
  titleKhmer: string;
  titleEnglish?: string;
  dateFrom: string; // YYYY-MM-DD
  dateTo: string;   // YYYY-MM-DD
  type: HolidayType;
  isDayOff: boolean;
  description?: string;
  academicYear?: string;
  lunarDetail?: string;
  isAutoGenerated?: boolean;
}

/**
 * Convert numbers to Khmer numerals (e.g. 2026 -> ២០២៦)
 */
export function toKhmerNumber(num: number | string): string {
  const khmerDigits = ['០', '១', '២', '៣', '៤', '៥', '៦', '៧', '៨', '៩'];
  return String(num).replace(/[0-9]/g, (digit) => khmerDigits[parseInt(digit, 10)]);
}

/**
 * Get Buddhist Era (ពុទ្ធសករាជ) from Gregorian Year
 * Cambodia official calendar: Gregorian year + 544 (e.g. 2026 -> 2570)
 */
export function getBuddhistYear(gregorianYear: number): number {
  return gregorianYear + 544;
}

/**
 * Format academic year string in Khmer, e.g. "២០២៥ - ២០២៦"
 */
export function formatAcademicYear(startYear: number): string {
  return `${toKhmerNumber(startYear)} - ${toKhmerNumber(startYear + 1)}`;
}

/**
 * High-precision official Khmer Lunar & Traditional Holidays table (2024 - 2035)
 * Based on official Royal Government of Cambodia Sub-decrees (អនុក្រឹត្យ) and Buddhist calendar
 */
interface LunarHolidayConfig {
  khmerNewYear: { from: string; to: string; days: number };
  visakBochea: string;
  royalPlowing: string;
  pchumBen: { from: string; to: string };
  waterFestival: { from: string; to: string };
}

const OFFICIAL_LUNAR_TABLE: Record<number, LunarHolidayConfig> = {
  2024: {
    khmerNewYear: { from: '2024-04-13', to: '2024-04-16', days: 4 },
    visakBochea: '2024-05-22',
    royalPlowing: '2024-05-26',
    pchumBen: { from: '2024-10-01', to: '2024-10-03' },
    waterFestival: { from: '2024-11-14', to: '2024-11-16' },
  },
  2025: {
    khmerNewYear: { from: '2025-04-14', to: '2025-04-16', days: 3 },
    visakBochea: '2025-05-12',
    royalPlowing: '2025-05-16',
    pchumBen: { from: '2025-09-21', to: '2025-09-23' },
    waterFestival: { from: '2025-11-04', to: '2025-11-06' },
  },
  2026: {
    khmerNewYear: { from: '2026-04-14', to: '2026-04-16', days: 3 },
    visakBochea: '2026-05-01',
    royalPlowing: '2026-05-05',
    pchumBen: { from: '2026-10-10', to: '2026-10-12' },
    waterFestival: { from: '2026-11-23', to: '2026-11-25' },
  },
  2027: {
    khmerNewYear: { from: '2027-04-14', to: '2027-04-16', days: 3 },
    visakBochea: '2027-05-20',
    royalPlowing: '2027-05-24',
    pchumBen: { from: '2027-09-29', to: '2027-10-01' },
    waterFestival: { from: '2027-11-12', to: '2027-11-14' },
  },
  2028: {
    khmerNewYear: { from: '2028-04-13', to: '2028-04-16', days: 4 },
    visakBochea: '2028-05-08',
    royalPlowing: '2028-05-12',
    pchumBen: { from: '2028-09-18', to: '2028-09-20' },
    waterFestival: { from: '2028-10-31', to: '2028-11-02' },
  },
  2029: {
    khmerNewYear: { from: '2029-04-14', to: '2029-04-16', days: 3 },
    visakBochea: '2029-05-27',
    royalPlowing: '2029-05-31',
    pchumBen: { from: '2029-10-07', to: '2029-10-09' },
    waterFestival: { from: '2029-11-19', to: '2029-11-21' },
  },
  2030: {
    khmerNewYear: { from: '2030-04-14', to: '2030-04-16', days: 3 },
    visakBochea: '2030-05-16',
    royalPlowing: '2030-05-20',
    pchumBen: { from: '2030-09-26', to: '2030-09-28' },
    waterFestival: { from: '2030-11-09', to: '2030-11-11' },
  },
  2031: {
    khmerNewYear: { from: '2031-04-14', to: '2031-04-16', days: 3 },
    visakBochea: '2031-05-06',
    royalPlowing: '2031-05-10',
    pchumBen: { from: '2031-09-16', to: '2031-09-18' },
    waterFestival: { from: '2031-10-29', to: '2031-10-31' },
  },
  2032: {
    khmerNewYear: { from: '2032-04-13', to: '2032-04-16', days: 4 },
    visakBochea: '2032-05-23',
    royalPlowing: '2032-05-27',
    pchumBen: { from: '2032-10-04', to: '2032-10-06' },
    waterFestival: { from: '2032-11-16', to: '2032-11-18' },
  },
  2033: {
    khmerNewYear: { from: '2033-04-14', to: '2033-04-16', days: 3 },
    visakBochea: '2033-05-13',
    royalPlowing: '2033-05-17',
    pchumBen: { from: '2033-09-23', to: '2033-09-25' },
    waterFestival: { from: '2033-11-06', to: '2033-11-08' },
  },
  2034: {
    khmerNewYear: { from: '2034-04-14', to: '2034-04-16', days: 3 },
    visakBochea: '2034-05-02',
    royalPlowing: '2034-05-06',
    pchumBen: { from: '2034-10-12', to: '2034-10-14' },
    waterFestival: { from: '2034-11-24', to: '2034-11-26' },
  },
  2035: {
    khmerNewYear: { from: '2035-04-14', to: '2035-04-16', days: 3 },
    visakBochea: '2035-05-21',
    royalPlowing: '2035-05-25',
    pchumBen: { from: '2035-10-01', to: '2035-10-03' },
    waterFestival: { from: '2035-11-14', to: '2035-11-16' },
  },
};

/**
 * Astronomical Fallback Algorithm for any year beyond 2035
 * Computes approximate full moons based on the mean synodic month cycle (29.53058885 days).
 */
function getApproximateLunarDates(year: number): LunarHolidayConfig {
  // Epoch reference: Jan 11, 2024 New Moon (Julian Day ~ 2460320.5)
  // Approximate full moon of Pisakh (May)
  const baseDateMay = new Date(Date.UTC(year, 4, 15));
  const baseDatePchum = new Date(Date.UTC(year, 8, 25));
  const baseDateWater = new Date(Date.UTC(year, 10, 10));

  const fmt = (d: Date) => d.toISOString().split('T')[0];
  const addDays = (d: Date, days: number) => {
    const res = new Date(d);
    res.setDate(res.getDate() + days);
    return res;
  };

  return {
    khmerNewYear: { from: `${year}-04-14`, to: `${year}-04-16`, days: 3 },
    visakBochea: fmt(baseDateMay),
    royalPlowing: fmt(addDays(baseDateMay, 4)),
    pchumBen: { from: fmt(baseDatePchum), to: fmt(addDays(baseDatePchum, 2)) },
    waterFestival: { from: fmt(baseDateWater), to: fmt(addDays(baseDateWater, 2)) },
  };
}

/**
 * Find the Nth weekday in a given month (e.g. 1st Monday of March)
 */
function getNthWeekdayOfMonth(year: number, month: number, weekday: number, n: number): Date {
  const d = new Date(year, month, 1);
  let count = 0;
  while (d.getMonth() === month) {
    if (d.getDay() === weekday) {
      count++;
      if (count === n) return new Date(d);
    }
    d.setDate(d.getDate() + 1);
  }
  return new Date(year, month, 1);
}

function formatDateStr(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

/**
 * Generate all official Cambodian Public Holidays & MoEYS Academic Calendar Events for a given calendar year
 */
export function generateCambodiaHolidaysForYear(year: number): HolidayData[] {
  const lunar = OFFICIAL_LUNAR_TABLE[year] || getApproximateLunarDates(year);
  const prevYearAcademic = formatAcademicYear(year - 1);
  const currentYearAcademic = formatAcademicYear(year);

  // Calculate Academic Calendar Dates dynamically
  // 1. Semester 1 Exam: 1st Monday of March (5 days: Mon-Fri)
  const sem1ExamStart = getNthWeekdayOfMonth(year, 2, 1, 1); // 1st Monday of March
  const sem1ExamEnd = new Date(sem1ExamStart);
  sem1ExamEnd.setDate(sem1ExamStart.getDate() + 4);

  // 2. Short Vacation: around Khmer New Year (covers 2 weeks in April)
  const vacationStart = new Date(year, 3, 7); // April 7
  const vacationEnd = new Date(year, 3, 20);   // April 20

  // 3. Semester 2 Exam: 1st Monday of July (5 days: Mon-Fri)
  const sem2ExamStart = getNthWeekdayOfMonth(year, 6, 1, 1); // 1st Monday of July
  const sem2ExamEnd = new Date(sem2ExamStart);
  sem2ExamEnd.setDate(sem2ExamStart.getDate() + 4);

  // 4. Grade 9 Diploma Exam: last Monday of July (2 days)
  const dipStart = new Date(year, 6, 25);
  while (dipStart.getDay() !== 1 && dipStart.getDate() <= 31) {
    dipStart.setDate(dipStart.getDate() + 1);
  }
  const dipEnd = new Date(dipStart);
  dipEnd.setDate(dipStart.getDate() + 1);

  // 5. Grade 12 Bac II National Exam: 3rd Monday of August (2 days)
  const bac2Start = getNthWeekdayOfMonth(year, 7, 1, 3); // 3rd Monday of August
  const bac2End = new Date(bac2Start);
  bac2End.setDate(bac2Start.getDate() + 1);

  const holidays: HolidayData[] = [
    // ------------------------------------------------------------------------
    // 1. FIXED SOLAR PUBLIC HOLIDAYS (អនុក្រឹត្យរាជរដ្ឋាភិបាល)
    // ------------------------------------------------------------------------
    {
      id: `hol-new-year-${year}`,
      titleKhmer: 'ទិវាចូលឆ្នាំសកល',
      titleEnglish: 'International New Year Day',
      dateFrom: `${year}-01-01`,
      dateTo: `${year}-01-01`,
      type: 'PUBLIC_HOLIDAY',
      isDayOff: true,
      description: 'ទិវាចូលឆ្នាំថ្មីសកល ១ មករា (ថ្ងៃឈប់សម្រាកការងារផ្លូវការ)',
      academicYear: prevYearAcademic,
      isAutoGenerated: true,
    },
    {
      id: `hol-victory-day-${year}`,
      titleKhmer: 'ទិវាជ័យជម្នះលើរបបប្រល័យពូជសាសន៍',
      titleEnglish: 'Victory Day over Genocide',
      dateFrom: `${year}-01-07`,
      dateTo: `${year}-01-07`,
      type: 'PUBLIC_HOLIDAY',
      isDayOff: true,
      description: 'ទិវា ៧ មករា ជ័យជម្នះលើរបបប្រល័យពូជសាសន៍',
      academicYear: prevYearAcademic,
      isAutoGenerated: true,
    },
    {
      id: `hol-women-day-${year}`,
      titleKhmer: 'ទិវាអន្តរជាតិនារី ៨ មីនា',
      titleEnglish: 'International Women Day',
      dateFrom: `${year}-03-08`,
      dateTo: `${year}-03-08`,
      type: 'PUBLIC_HOLIDAY',
      isDayOff: true,
      description: 'ទិវាសិទ្ធិនារីអន្តរជាតិ ៨ មីនា',
      academicYear: prevYearAcademic,
      isAutoGenerated: true,
    },
    {
      id: `hol-labor-day-${year}`,
      titleKhmer: 'ទិវាពលកម្មអន្តរជាតិ ១ ឧសភា',
      titleEnglish: 'International Labor Day',
      dateFrom: `${year}-05-01`,
      dateTo: `${year}-05-01`,
      type: 'PUBLIC_HOLIDAY',
      isDayOff: true,
      description: 'ទិវាពលកម្មអន្តរជាតិ ១ ឧសភា',
      academicYear: prevYearAcademic,
      isAutoGenerated: true,
    },
    {
      id: `hol-king-birthday-${year}`,
      titleKhmer: 'ព្រះរាជពិធីបុណ្យចម្រើនព្រះជន្ម ព្រះករុណា ព្រះបាទសម្តេចព្រះបរមនាថ នរោត្តម សីហមុនី',
      titleEnglish: 'King Norodom Sihamoni Birthday',
      dateFrom: `${year}-05-14`,
      dateTo: `${year}-05-14`,
      type: 'PUBLIC_HOLIDAY',
      isDayOff: true,
      description: 'ព្រះរាជពិធីបុណ្យចម្រើនព្រះជន្ម ព្រះមហាក្សត្រនៃព្រះរាជាណាចក្រកម្ពុជា ១៤ ឧសភា',
      academicYear: prevYearAcademic,
      isAutoGenerated: true,
    },
    {
      id: `hol-queen-mother-birthday-${year}`,
      titleKhmer: 'ព្រះរាជពិធីបុណ្យចម្រើនព្រះជន្ម សម្តេចព្រះមហាក្សត្រី នរោត្តម មុនិនាថ សីហនុ ព្រះវររាជមាតាជាតិខ្មែរ',
      titleEnglish: 'Queen Mother Norodom Monineath Sihanouk Birthday',
      dateFrom: `${year}-06-18`,
      dateTo: `${year}-06-18`,
      type: 'PUBLIC_HOLIDAY',
      isDayOff: true,
      description: 'ព្រះរាជពិធីបុណ្យចម្រើនព្រះជន្ម សម្តេចម៉ែ ១៨ មិថុនា',
      academicYear: prevYearAcademic,
      isAutoGenerated: true,
    },
    {
      id: `hol-constitution-day-${year}`,
      titleKhmer: 'ទិវាប្រកាសរដ្ឋធម្មនុញ្ញ ២៤ កញ្ញា',
      titleEnglish: 'Constitutional Day',
      dateFrom: `${year}-09-24`,
      dateTo: `${year}-09-24`,
      type: 'PUBLIC_HOLIDAY',
      isDayOff: true,
      description: 'ទិវាប្រកាសរដ្ឋធម្មនុញ្ញនៃព្រះរាជាណាចក្រកម្ពុជា ២៤ កញ្ញា',
      academicYear: prevYearAcademic,
      isAutoGenerated: true,
    },
    {
      id: `hol-commemoration-king-father-${year}`,
      titleKhmer: 'ទិវាប្រារព្ធពិធីគោរពព្រះវិញ្ញាណក្ខន្ធ ព្រះករុណា ព្រះបាទសម្តេចព្រះ នរោត្តម សីហនុ ព្រះបរមរតនកោដ្ឋ',
      titleEnglish: 'Commemoration Day of the King Father',
      dateFrom: `${year}-10-15`,
      dateTo: `${year}-10-15`,
      type: 'PUBLIC_HOLIDAY',
      isDayOff: true,
      description: 'ទិវាគោរពព្រះវិញ្ញាណក្ខន្ធ ព្រះបរមរតនកោដ្ឋ ១៥ តុលា',
      academicYear: prevYearAcademic,
      isAutoGenerated: true,
    },
    {
      id: `hol-coronation-day-${year}`,
      titleKhmer: 'ព្រះរាជពិធីគ្រងរាជសម្បត្តិ ព្រះករុណា ព្រះបាទសម្តេចព្រះបរមនាថ នរោត្តម សីហមុនី',
      titleEnglish: 'Coronation Day of King Sihamoni',
      dateFrom: `${year}-10-29`,
      dateTo: `${year}-10-29`,
      type: 'PUBLIC_HOLIDAY',
      isDayOff: true,
      description: 'ទិវាខួបនៃការគ្រងរាជសម្បត្តិព្រះមហាក្សត្រ ២៩ តុលា',
      academicYear: prevYearAcademic,
      isAutoGenerated: true,
    },
    {
      id: `hol-independence-day-${year}`,
      titleKhmer: `ពិធីបុណ្យឯករាជ្យជាតិ (ខួបលើកទី${year - 1953})`,
      titleEnglish: 'National Independence Day',
      dateFrom: `${year}-11-09`,
      dateTo: `${year}-11-09`,
      type: 'PUBLIC_HOLIDAY',
      isDayOff: true,
      description: 'ទិវាបុណ្យឯករាជ្យជាតិ ៩ វិច្ឆិកា នៃព្រះរាជាណាចក្រកម្ពុជា',
      academicYear: currentYearAcademic,
      isAutoGenerated: true,
    },
    {
      id: `hol-peace-day-${year}`,
      titleKhmer: 'ទិវាសន្តិភាពនៅកម្ពុជា ២៩ ធ្នូ',
      titleEnglish: 'Peace Day in Cambodia',
      dateFrom: `${year}-12-29`,
      dateTo: `${year}-12-29`,
      type: 'PUBLIC_HOLIDAY',
      isDayOff: true,
      description: 'ទិវាសន្តិភាពនៅកម្ពុជា ២៩ ធ្នូ (អនុក្រឹត្យរាជរដ្ឋាភិបាល)',
      academicYear: currentYearAcademic,
      isAutoGenerated: true,
    },

    // ------------------------------------------------------------------------
    // 2. KHMER LUNAR & TRADITIONAL PUBLIC HOLIDAYS (ពិធីបុណ្យប្រពៃណីជាតិ និងចន្ទគតិ)
    // ------------------------------------------------------------------------
    {
      id: `hol-khmer-new-year-${year}`,
      titleKhmer: 'ពិធីបុណ្យចូលឆ្នាំថ្មី ប្រពៃណីជាតិខ្មែរ',
      titleEnglish: 'Khmer New Year Days',
      dateFrom: lunar.khmerNewYear.from,
      dateTo: lunar.khmerNewYear.to,
      type: 'PUBLIC_HOLIDAY',
      isDayOff: true,
      description: `ពិធីបុណ្យចូលឆ្នាំថ្មីប្រពៃណីជាតិខ្មែរ រយៈពេល ${lunar.khmerNewYear.days} ថ្ងៃ`,
      lunarDetail: 'មហាសង្ក្រាន្ត វារៈវ័នបត វារៈឡើងស័ក',
      academicYear: prevYearAcademic,
      isAutoGenerated: true,
    },
    {
      id: `hol-visak-bochea-${year}`,
      titleKhmer: 'ពិធីបុណ្យវិសាខបូជា',
      titleEnglish: 'Visak Bochea Day',
      dateFrom: lunar.visakBochea,
      dateTo: lunar.visakBochea,
      type: 'PUBLIC_HOLIDAY',
      isDayOff: true,
      description: 'ទិវាបុណ្យសាសនាជាតិ វិសាខបូជា (១៥កើត ខែពិសាខ)',
      lunarDetail: '១៥កើត ខែពិសាខ',
      academicYear: prevYearAcademic,
      isAutoGenerated: true,
    },
    {
      id: `hol-royal-plowing-${year}`,
      titleKhmer: 'ព្រះរាជពិធីច្រត់ព្រះនង្គ័ល',
      titleEnglish: 'Royal Plowing Ceremony',
      dateFrom: lunar.royalPlowing,
      dateTo: lunar.royalPlowing,
      type: 'PUBLIC_HOLIDAY',
      isDayOff: true,
      description: 'ព្រះរាជពិធីច្រត់ព្រះនង្គ័ល (៤រោច ខែពិសាខ)',
      lunarDetail: '៤រោច ខែពិសាខ',
      academicYear: prevYearAcademic,
      isAutoGenerated: true,
    },
    {
      id: `hol-pchum-ben-${year}`,
      titleKhmer: 'ពិធីបុណ្យភ្ជុំបិណ្ឌ',
      titleEnglish: 'Pchum Ben Festival Days',
      dateFrom: lunar.pchumBen.from,
      dateTo: lunar.pchumBen.to,
      type: 'PUBLIC_HOLIDAY',
      isDayOff: true,
      description: 'ពិធីបុណ្យកាន់បិណ្ឌ និងភ្ជុំបិណ្ឌប្រពៃណីជាតិខ្មែរ រយៈពេល ៣ ថ្ងៃ',
      lunarDetail: '១៤-១៥រោច ខែភទ្របទ និង ១កើត ខែអស្សុជ',
      academicYear: prevYearAcademic,
      isAutoGenerated: true,
    },
    {
      id: `hol-water-festival-${year}`,
      titleKhmer: 'ព្រះរាជពិធីបុណ្យអុំទូក បណ្តែតប្រទីប និងសំពះព្រះខែ អកអំបុក',
      titleEnglish: 'Water and Moon Festival',
      dateFrom: lunar.waterFestival.from,
      dateTo: lunar.waterFestival.to,
      type: 'PUBLIC_HOLIDAY',
      isDayOff: true,
      description: 'ព្រះរាជពិធីបុណ្យអុំទូក បណ្តែតប្រទីប និងសំពះព្រះខែ អកអំបុក រយៈពេល ៣ ថ្ងៃ',
      lunarDetail: '១៤-១៥កើត និង ១រោច ខែកត្តិក',
      academicYear: currentYearAcademic,
      isAutoGenerated: true,
    },

    // ------------------------------------------------------------------------
    // 3. MoEYS CAMBODIA ACADEMIC CALENDAR EVENTS (កាលវិភាគអប់រំ និងការប្រឡង)
    // ------------------------------------------------------------------------
    {
      id: `moeys-exam-sem1-${year}`,
      titleKhmer: 'ការប្រឡងបញ្ចប់ឆមាសទី១',
      titleEnglish: 'Semester 1 Final Examination',
      dateFrom: formatDateStr(sem1ExamStart),
      dateTo: formatDateStr(sem1ExamEnd),
      type: 'EXAM_PERIOD',
      isDayOff: false,
      description: 'សម័យប្រឡងឆមាសទី១ សម្រាប់កម្រិតបឋមសិក្សា និងមធ្យមសិក្សា',
      academicYear: prevYearAcademic,
      isAutoGenerated: true,
    },
    {
      id: `moeys-break-sem1-${year}`,
      titleKhmer: 'វិស្សមកាលតូច (ដំណាច់ឆមាសទី១)',
      titleEnglish: 'Short Vacation / Mid-Year Break',
      dateFrom: formatDateStr(vacationStart),
      dateTo: formatDateStr(vacationEnd),
      type: 'VACATION',
      isDayOff: true,
      description: 'វិស្សមកាលតូច រួមទាំងពិធីបុណ្យចូលឆ្នាំថ្មីប្រពៃណីជាតិខ្មែរ',
      academicYear: prevYearAcademic,
      isAutoGenerated: true,
    },
    {
      id: `moeys-exam-sem2-${year}`,
      titleKhmer: 'ការប្រឡងបញ្ចប់ឆមាសទី២',
      titleEnglish: 'Semester 2 Final Examination',
      dateFrom: formatDateStr(sem2ExamStart),
      dateTo: formatDateStr(sem2ExamEnd),
      type: 'EXAM_PERIOD',
      isDayOff: false,
      description: 'សម័យប្រឡងឆមាសទី២ បញ្ចប់ឆ្នាំសិក្សា',
      academicYear: prevYearAcademic,
      isAutoGenerated: true,
    },
    {
      id: `moeys-exam-dip-${year}`,
      titleKhmer: 'ការប្រឡងសញ្ញាបត្រមធ្យមសិក្សាបឋមភូមិ (ឌីប្លូម)',
      titleEnglish: 'Lower Secondary Diploma Exam (Grade 9)',
      dateFrom: formatDateStr(dipStart),
      dateTo: formatDateStr(dipEnd),
      type: 'EXAM_PERIOD',
      isDayOff: false,
      description: 'សម័យប្រឡងឌីប្លូមថ្នាក់ទី ៩ ទូទាំងប្រទេស',
      academicYear: prevYearAcademic,
      isAutoGenerated: true,
    },
    {
      id: `moeys-summer-vacation-${year}`,
      titleKhmer: 'វិស្សមកាលធំ (ដំណាច់ឆ្នាំសិក្សា)',
      titleEnglish: 'Grand Vacation / Summer Recess',
      dateFrom: `${year}-08-01`,
      dateTo: `${year}-10-31`,
      type: 'VACATION',
      isDayOff: true,
      description: 'វិស្សមកាលធំ រយៈពេល ៣ ខែ សម្រាប់សិស្សានុសិស្ស និងលោកគ្រូ-អ្នកគ្រូ',
      academicYear: prevYearAcademic,
      isAutoGenerated: true,
    },
    {
      id: `moeys-exam-bac2-${year}`,
      titleKhmer: 'ការប្រឡងសញ្ញាបត្រមធ្យមសិក្សាទុតិយភូមិ (បាក់ឌុប)',
      titleEnglish: 'Upper Secondary National Exam (Bac II - Grade 12)',
      dateFrom: formatDateStr(bac2Start),
      dateTo: formatDateStr(bac2End),
      type: 'EXAM_PERIOD',
      isDayOff: false,
      description: 'សម័យប្រឡងសញ្ញាបត្របាក់ឌុបថ្នាក់ទី ១២ ទូទាំងប្រទេស',
      academicYear: prevYearAcademic,
      isAutoGenerated: true,
    },
    {
      id: `moeys-school-open-${year}`,
      titleKhmer: `ពិធីបើកបវេសនកាលឆ្នាំសិក្សាថ្មី ${currentYearAcademic}`,
      titleEnglish: `Opening of Academic Year ${year}-${year + 1}`,
      dateFrom: `${year}-11-01`,
      dateTo: `${year}-11-01`,
      type: 'ACADEMIC_EVENT',
      isDayOff: false,
      description: 'ថ្ងៃបើកបវេសនកាលផ្លូវការគ្រប់គ្រឹះស្ថានសិក្សាចំណេះទូទៅទូទាំងប្រទេស',
      academicYear: currentYearAcademic,
      isAutoGenerated: true,
    },
  ];

  return holidays.sort((a, b) => a.dateFrom.localeCompare(b.dateFrom));
}

/**
 * Generate holidays for a range of years, e.g. 2024 through 2028
 */
export function generateCambodiaHolidaysForYearRange(startYear: number, endYear: number): HolidayData[] {
  const all: HolidayData[] = [];
  for (let y = startYear; y <= endYear; y++) {
    all.push(...generateCambodiaHolidaysForYear(y));
  }
  return all.sort((a, b) => a.dateFrom.localeCompare(b.dateFrom));
}

/**
 * Check and ensure that holidays for a target year exist in the provided holiday list.
 * Returns the merged list and count of newly added holidays.
 */
export function ensureHolidaysForYear(
  existingHolidays: HolidayData[],
  targetYear: number
): { updatedHolidays: HolidayData[]; addedCount: number } {
  const existingMap = new Map<string, HolidayData>();
  existingHolidays.forEach((h) => existingMap.set(h.id, h));

  const generated = generateCambodiaHolidaysForYear(targetYear);
  let addedCount = 0;

  generated.forEach((gen) => {
    // If exact ID exists, do not overwrite custom edits
    if (!existingMap.has(gen.id)) {
      // Also verify no duplicate date & title exists
      const hasConflict = existingHolidays.some(
        (h) => h.dateFrom === gen.dateFrom && h.titleKhmer === gen.titleKhmer
      );
      if (!hasConflict) {
        existingMap.set(gen.id, gen);
        addedCount++;
      }
    }
  });

  const updatedHolidays = Array.from(existingMap.values()).sort((a, b) =>
    a.dateFrom.localeCompare(b.dateFrom)
  );

  return { updatedHolidays, addedCount };
}

/**
 * Check and ensure holidays for both current year and next years (currentYear .. currentYear + 2).
 * Automatically invoked when loading the calendar or switching academic years.
 */
export function ensureHolidaysForCurrentAndNextYears(
  existingHolidays: HolidayData[]
): { updatedHolidays: HolidayData[]; addedCount: number } {
  const currentYear = new Date().getFullYear();
  let currentList = [...existingHolidays];
  let totalAdded = 0;

  for (let y = currentYear - 1; y <= currentYear + 2; y++) {
    const { updatedHolidays, addedCount } = ensureHolidaysForYear(currentList, y);
    currentList = updatedHolidays;
    totalAdded += addedCount;
  }

  return { updatedHolidays: currentList, addedCount: totalAdded };
}

/**
 * Default multi-year holidays covering 2024 through currentYear + 2
 */
export const DEFAULT_CAMBODIA_HOLIDAYS: HolidayData[] = generateCambodiaHolidaysForYearRange(
  2024,
  Math.max(2027, new Date().getFullYear() + 2)
);

/**
 * Backward compatibility alias for 2024-2025
 */
export const OFFICIAL_CAMBODIA_HOLIDAYS_2024_2025: HolidayData[] = DEFAULT_CAMBODIA_HOLIDAYS;
