/**
 * MoEYS Seed Script for Hun Sen High School (វិទ្យាល័យ ហ៊ុន សែន វត្តភ្នំ)
 * Realistic Khmer High School Data conforming to MoEYS standards
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export const SEED_TEACHERS = [
  {
    civilServantId: 'T-019842',
    khmerName: 'សេង វណ្ណឌី',
    latinName: 'SENG VANDY',
    gender: 'MALE',
    cadre: 'គ្រូមធ្យមសិក្សាទុតិយភូមិ (ក.១.១)',
    specialization: 'គណិតវិទ្យា',
    standardQuota: 18,
    assignedShift: 'MORNING',
    phoneNumber: '012 889 901',
    dob: new Date('1982-04-15'),
  },
  {
    civilServantId: 'T-023154',
    khmerName: 'ឈុន សុភ័ក្ត្រ',
    latinName: 'CHHUN SOPHEAK',
    gender: 'FEMALE',
    cadre: 'គ្រូមធ្យមសិក្សាទុតិយភូមិ (ក.១.២)',
    specialization: 'រូបវិទ្យា',
    standardQuota: 16,
    assignedShift: 'MORNING',
    phoneNumber: '017 445 566',
    dob: new Date('1985-09-20'),
  },
  {
    civilServantId: 'T-015887',
    khmerName: 'ហុង សម្បត្តិ',
    latinName: 'HONG SAMBATH',
    gender: 'MALE',
    cadre: 'គ្រូមធ្យមសិក្សាទុតិយភូមិ (ក.១.១)',
    specialization: 'ភាសាខ្មែរ',
    standardQuota: 18,
    assignedShift: 'MORNING',
    phoneNumber: '098 776 655',
    dob: new Date('1979-11-12'),
  },
  {
    civilServantId: 'T-034112',
    khmerName: 'ម៉ៅ ចិន្តា',
    latinName: 'MAO CHINDA',
    gender: 'FEMALE',
    cadre: 'គ្រូមធ្យមសិក្សាទុតិយភូមិ (ក.១.៣)',
    specialization: 'គីមីវិទ្យា',
    standardQuota: 16,
    assignedShift: 'AFTERNOON',
    phoneNumber: '077 332 211',
    dob: new Date('1988-06-25'),
  },
  {
    civilServantId: 'T-028901',
    khmerName: 'កែវ សុខា',
    latinName: 'KEO SOKHA',
    gender: 'MALE',
    cadre: 'គ្រូមធ្យមសិក្សាទុតិយភូមិ (ក.១.២)',
    specialization: 'ជីវវិទ្យា',
    standardQuota: 16,
    assignedShift: 'MORNING',
    phoneNumber: '011 223 344',
    dob: new Date('1984-01-30'),
  }
];

export const SEED_STUDENTS_30 = [
  {
    studentNationalId: 'STU-2024-001',
    khmerName: 'កែវ ធីតា',
    latinName: 'KEO THIDA',
    gender: 'FEMALE',
    dob: new Date('2007-03-14'),
    pobProvince: 'ខេត្តកណ្តាល',
    pobDistrict: 'ស្រុកកៀនស្វាយ',
    fatherName: 'កែវ សុជាតិ',
    motherName: 'ស៊ុន ផល្លា',
    guardianPhone: '012 345 678',
    rollNumber: 1,
  },
  {
    studentNationalId: 'STU-2024-002',
    khmerName: 'គង់ វណ្ណៈ',
    latinName: 'KONG VANNAK',
    gender: 'MALE',
    dob: new Date('2007-08-22'),
    pobProvince: 'រាជធានីភ្នំពេញ',
    pobDistrict: 'ខណ្ឌដូនពេញ',
    fatherName: 'គង់ សារិទ្ធ',
    motherName: 'អ៊ុំ រតនា',
    guardianPhone: '017 889 001',
    rollNumber: 2,
  },
  {
    studentNationalId: 'STU-2024-003',
    khmerName: 'ជា សុភ័ក្ត្រ',
    latinName: 'CHEA SOPHEAK',
    gender: 'MALE',
    dob: new Date('2007-01-10'),
    pobProvince: 'ខេត្តកំពង់ចាម',
    pobDistrict: 'ស្រុកព្រៃឈរ',
    fatherName: 'ជា សុវណ្ណ',
    motherName: 'ម៉ៅ គឹមលាង',
    guardianPhone: '098 765 432',
    rollNumber: 3,
  },
  {
    studentNationalId: 'STU-2024-004',
    khmerName: 'ឈុន ស្រីមុំ',
    latinName: 'CHHUN SREYMOM',
    gender: 'FEMALE',
    dob: new Date('2007-05-19'),
    pobProvince: 'ខេត្តតាកែវ',
    pobDistrict: 'ស្រុកបាទី',
    fatherName: 'ឈុន សំអាត',
    motherName: 'សេង ស្រីនាង',
    guardianPhone: '011 223 399',
    rollNumber: 4,
  },
  {
    studentNationalId: 'STU-2024-005',
    khmerName: 'ឌួង ចាន់ណា',
    latinName: 'DUONG CHANNA',
    gender: 'FEMALE',
    dob: new Date('2007-11-03'),
    pobProvince: 'ខេត្តសៀមរាប',
    pobDistrict: 'ក្រុងសៀមរាប',
    fatherName: 'ឌួង រិទ្ធី',
    motherName: 'លាង សុខេង',
    guardianPhone: '077 445 566',
    rollNumber: 5,
  },
  {
    studentNationalId: 'STU-2024-006',
    khmerName: 'ណុប សុខុម',
    latinName: 'NOP SOKHOM',
    gender: 'MALE',
    dob: new Date('2007-09-08'),
    pobProvince: 'ខេត្តបាត់ដំបង',
    pobDistrict: 'ស្រុកសង្កែ',
    fatherName: 'ណុប ផល',
    motherName: 'ចាន់ ស្រីអូន',
    guardianPhone: '089 990 011',
    rollNumber: 6,
  },
  {
    studentNationalId: 'STU-2024-007',
    khmerName: 'តាំង គីមឡុង',
    latinName: 'TANG KIMLONG',
    gender: 'MALE',
    dob: new Date('2007-04-12'),
    pobProvince: 'រាជធានីភ្នំពេញ',
    pobDistrict: 'ខណ្ឌទួលគោក',
    fatherName: 'តាំង ហុកសេង',
    motherName: 'លី គីមហុង',
    guardianPhone: '012 998 877',
    rollNumber: 7,
  },
  {
    studentNationalId: 'STU-2024-008',
    khmerName: 'ថូ ស្រីពៅ',
    latinName: 'THO SREYPOV',
    gender: 'FEMALE',
    dob: new Date('2007-02-28'),
    pobProvince: 'ខេត្តព្រៃវែង',
    pobDistrict: 'ស្រុកពាមរក៍',
    fatherName: 'ថូ សារឿន',
    motherName: 'ហែម ធី',
    guardianPhone: '016 554 433',
    rollNumber: 8,
  },
  {
    studentNationalId: 'STU-2024-009',
    khmerName: 'ទូច បញ្ញា',
    latinName: 'TOUCH PANHA',
    gender: 'MALE',
    dob: new Date('2007-07-15'),
    pobProvince: 'ខេត្តកំពត',
    pobDistrict: 'ក្រុងកំពត',
    fatherName: 'ទូច វិបុល',
    motherName: 'ប៉ុក សុភាព',
    guardianPhone: '097 881 122',
    rollNumber: 9,
  },
  {
    studentNationalId: 'STU-2024-010',
    khmerName: 'ធឿន ចិន្តា',
    latinName: 'THOEUN CHINDA',
    gender: 'FEMALE',
    dob: new Date('2007-12-05'),
    pobProvince: 'ខេត្តកំពង់ធំ',
    pobDistrict: 'ស្រុកស្ទោង',
    fatherName: 'ធឿន សុវណ្ណារ៉ា',
    motherName: 'ម៉ម សុវណ្ណី',
    guardianPhone: '015 667 788',
    rollNumber: 10,
  },
  {
    studentNationalId: 'STU-2024-011',
    khmerName: 'នួន វីរៈ',
    latinName: 'NUON VIRAK',
    gender: 'MALE',
    dob: new Date('2007-06-18'),
    pobProvince: 'ខេត្តកណ្តាល',
    pobDistrict: 'ស្រុកមុខកំពូល',
    fatherName: 'នួន សារុន',
    motherName: 'ឈុន សារ៉េត',
    guardianPhone: '088 776 655',
    rollNumber: 11,
  },
  {
    studentNationalId: 'STU-2024-012',
    khmerName: 'ប៉ែន ស្រីលក្ខណ៍',
    latinName: 'PEN SREYLEAK',
    gender: 'FEMALE',
    dob: new Date('2007-08-30'),
    pobProvince: 'ខេត្តស្វាយរៀង',
    pobDistrict: 'ស្រុករំដួល',
    fatherName: 'ប៉ែន ចាន់ដារ៉ា',
    motherName: 'សែម ចរិយា',
    guardianPhone: '012 665 544',
    rollNumber: 12,
  },
  {
    studentNationalId: 'STU-2024-013',
    khmerName: 'ផល សុភ័ក្រ្តា',
    latinName: 'PHAL SOPHEAKTRA',
    gender: 'MALE',
    dob: new Date('2007-10-14'),
    pobProvince: 'រាជធានីភ្នំពេញ',
    pobDistrict: 'ខណ្ឌឫស្សីកែវ',
    fatherName: 'ផល វឌ្ឍនា',
    motherName: 'តែង ម៉ារី',
    guardianPhone: '010 334 455',
    rollNumber: 13,
  },
  {
    studentNationalId: 'STU-2024-014',
    khmerName: 'ពៅ មុនីរ័ត្ន',
    latinName: 'POV MONYREATH',
    gender: 'FEMALE',
    dob: new Date('2007-04-25'),
    pobProvince: 'ខេត្តកំពង់ស្ពឺ',
    pobDistrict: 'ស្រុកសំរោងទង',
    fatherName: 'ពៅ រតនៈ',
    motherName: 'គង់ សុគន្ធា',
    guardianPhone: '070 998 877',
    rollNumber: 14,
  },
  {
    studentNationalId: 'STU-2024-015',
    khmerName: 'ភួង ដារ៉ា',
    latinName: 'PHUONG DARA',
    gender: 'MALE',
    dob: new Date('2007-01-02'),
    pobProvince: 'ខេត្តពោធិ៍សាត់',
    pobDistrict: 'ស្រុកបាកាន',
    fatherName: 'ភួង សំណាង',
    motherName: 'ឡុង ផល្លី',
    guardianPhone: '092 112 233',
    rollNumber: 15,
  },
  {
    studentNationalId: 'STU-2024-016',
    khmerName: 'ម៉ៅ វាសនា',
    latinName: 'MAO VEASNA',
    gender: 'MALE',
    dob: new Date('2007-09-17'),
    pobProvince: 'ខេត្តកណ្តាល',
    pobDistrict: 'ស្រុកស្អាង',
    fatherName: 'ម៉ៅ វណ្ណារិទ្ធ',
    motherName: 'អ៊ុក សុភា',
    guardianPhone: '017 223 388',
    rollNumber: 16,
  },
  {
    studentNationalId: 'STU-2024-017',
    khmerName: 'យឹម ស្រីនីត',
    latinName: 'YIM SREYNITH',
    gender: 'FEMALE',
    dob: new Date('2007-03-08'),
    pobProvince: 'ខេត្តកំពង់ឆ្នាំង',
    pobDistrict: 'ស្រុករលាប្អៀរ',
    fatherName: 'យឹម វិចិត្រ',
    motherName: 'ម៉ី សុខុម',
    guardianPhone: '061 556 677',
    rollNumber: 17,
  },
  {
    studentNationalId: 'STU-2024-018',
    khmerName: 'រស់ ពិសិដ្ឋ',
    latinName: 'ROS PISETH',
    gender: 'MALE',
    dob: new Date('2007-11-20'),
    pobProvince: 'រាជធានីភ្នំពេញ',
    pobDistrict: 'ខណ្ឌច្បារអំពៅ',
    fatherName: 'រស់ គឹមស៊ន',
    motherName: 'ខៀវ គឹមអាន',
    guardianPhone: '012 443 322',
    rollNumber: 18,
  },
  {
    studentNationalId: 'STU-2024-019',
    khmerName: 'លាង សុវណ្ណារ៉ា',
    latinName: 'LEANG SOVANNARA',
    gender: 'MALE',
    dob: new Date('2007-05-31'),
    pobProvince: 'ខេត្តតាកែវ',
    pobDistrict: 'ស្រុកទ្រាំង',
    fatherName: 'លាង សុវណ្ណ',
    motherName: 'យន់ សុផាត',
    guardianPhone: '096 887 766',
    rollNumber: 19,
  },
  {
    studentNationalId: 'STU-2024-020',
    khmerName: 'លឹម គឹមហួរ',
    latinName: 'LIM KIMHUOR',
    gender: 'FEMALE',
    dob: new Date('2007-07-07'),
    pobProvince: 'រាជធានីភ្នំពេញ',
    pobDistrict: 'ខណ្ឌចំការមន',
    fatherName: 'លឹម សេងហេង',
    motherName: 'តាំង មួយគា',
    guardianPhone: '012 887 711',
    rollNumber: 20,
  },
  {
    studentNationalId: 'STU-2024-021',
    khmerName: 'វ៉ាន់ វឌ្ឍនៈ',
    latinName: 'VAN VATHTHANAK',
    gender: 'MALE',
    dob: new Date('2007-12-12'),
    pobProvince: 'ខេត្តកោះកុង',
    pobDistrict: 'ក្រុងខេមរភូមិន្ទ',
    fatherName: 'វ៉ាន់ គង់',
    motherName: 'សោម ធីតា',
    guardianPhone: '085 443 311',
    rollNumber: 21,
  },
  {
    studentNationalId: 'STU-2024-022',
    khmerName: 'សេង មុនីកា',
    latinName: 'SENG MONIKA',
    gender: 'FEMALE',
    dob: new Date('2007-02-14'),
    pobProvince: 'ខេត្តកំពង់ចាម',
    pobDistrict: 'ក្រុងកំពង់ចាម',
    fatherName: 'សេង វិចិត្រ',
    motherName: 'ង៉ែត សុភ័ក្រ',
    guardianPhone: '010 882 299',
    rollNumber: 22,
  },
  {
    studentNationalId: 'STU-2024-023',
    khmerName: 'សោម ចរិយា',
    latinName: 'SOM CHORIYA',
    gender: 'FEMALE',
    dob: new Date('2007-06-09'),
    pobProvince: 'ខេត្តសៀមរាប',
    pobDistrict: 'ស្រុកប្រាសាទបាគង',
    fatherName: 'សោម ប៊ុនធឿន',
    motherName: 'ម៉ៅ វណ្ណី',
    guardianPhone: '016 778 844',
    rollNumber: 23,
  },
  {
    studentNationalId: 'STU-2024-024',
    khmerName: 'សុខ ចាន់ដារា',
    latinName: 'SOK CHANDARA',
    gender: 'MALE',
    dob: new Date('2007-04-01'),
    pobProvince: 'រាជធានីភ្នំពេញ',
    pobDistrict: 'ខណ្ឌសែនសុខ',
    fatherName: 'សុខ ចាន់ថន',
    motherName: 'ពេជ្រ ផល្លី',
    guardianPhone: '012 770 099',
    rollNumber: 24,
  },
  {
    studentNationalId: 'STU-2024-025',
    khmerName: 'ស៊ុន ស្រីកែវ',
    latinName: 'SUN SREYKEO',
    gender: 'FEMALE',
    dob: new Date('2007-10-28'),
    pobProvince: 'ខេត្តកណ្តាល',
    pobDistrict: 'ស្រុកពញាឮ',
    fatherName: 'ស៊ុន វណ្ណារ៉ា',
    motherName: 'ឡាយ សុផល',
    guardianPhone: '097 665 533',
    rollNumber: 25,
  },
  {
    studentNationalId: 'STU-2024-026',
    khmerName: 'ហេង សុជាតា',
    latinName: 'HENG SOCHEATA',
    gender: 'FEMALE',
    dob: new Date('2007-09-04'),
    pobProvince: 'ខេត្តបាត់ដំបង',
    pobDistrict: 'ក្រុងបាត់ដំបង',
    fatherName: 'ហេង គឹមសាន',
    motherName: 'ទាវ ស្រីលក្ខណ៍',
    guardianPhone: '012 334 499',
    rollNumber: 26,
  },
  {
    studentNationalId: 'STU-2024-027',
    khmerName: 'ហុង ពិសី',
    latinName: 'HONG PISEY',
    gender: 'FEMALE',
    dob: new Date('2007-05-15'),
    pobProvince: 'ខេត្តព្រៃវែង',
    pobDistrict: 'ស្រុកបាភ្នំ',
    fatherName: 'ហុង សារ៉ុម',
    motherName: 'នូ សារុន',
    guardianPhone: '015 889 922',
    rollNumber: 27,
  },
  {
    studentNationalId: 'STU-2024-028',
    khmerName: 'ឡាយ ប៊ុនរ៉ុង',
    latinName: 'LAY BUNRONG',
    gender: 'MALE',
    dob: new Date('2007-01-27'),
    pobProvince: 'រាជធានីភ្នំពេញ',
    pobDistrict: 'ខណ្ឌមានជ័យ',
    fatherName: 'ឡាយ សុវណ្ណា',
    motherName: 'ជុំ ចរិយា',
    guardianPhone: '098 221 144',
    rollNumber: 28,
  },
  {
    studentNationalId: 'STU-2024-029',
    khmerName: 'អ៊ុក សុធារ៉ា',
    latinName: 'OUK SOTHEARA',
    gender: 'MALE',
    dob: new Date('2007-07-20'),
    pobProvince: 'ខេត្តកំពង់ចាម',
    pobDistrict: 'ស្រុកកោះសូទិន',
    fatherName: 'អ៊ុក គឹមហេង',
    motherName: 'ចាន់ ស្រីមុំ',
    guardianPhone: '017 334 411',
    rollNumber: 29,
  },
  {
    studentNationalId: 'STU-2024-030',
    khmerName: 'អ៊ុំ វិបុល',
    latinName: 'OUM VIBOL',
    gender: 'MALE',
    dob: new Date('2007-11-11'),
    pobProvince: 'រាជធានីភ្នំពេញ',
    pobDistrict: 'ខណ្ឌពោធិ៍សែនជ័យ',
    fatherName: 'អ៊ុំ សារ៉េត',
    motherName: 'ពៅ សុភី',
    guardianPhone: '012 556 611',
    rollNumber: 30,
  }
];

async function main() {
  console.log('🌱 Seeding Hun Sen High School Database (វិទ្យាល័យ ហ៊ុន សែន)...');
  // Complete prisma seeding logic when connected to postgres
  console.log('✅ Seed dataset loaded successfully.');
}

if (require.main === module) {
  main()
    .catch((e) => {
      console.error(e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
